try {
    let teste = a+b
    console.log(teste)
} catch(error) {
    console.log(`Deu o erro: ${error} `)
}